apiVersion: appstudio.redhat.com/v1alpha1
kind: IntegrationTestScenario
metadata:
  name: example-fail
  namespace: default
spec:
  application: application-sample
  bundle: 'quay.io/kpavic/test-bundle:component-pipeline-fail'
  pipeline: component-pipeline-fail