apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-output
spec:
  results:
    - name: HACBS_TEST_OUTPUT
      description: Test output
  params:
    - name: TEST_SUITE_NAME
      description: Test suite name
    - default: "SUCCESS"
      name: RESULT
      description: Test result to be generated
    - default: "0"
      name: SUCCESSES
      description: Number of test result successes
    - default: "0"
      name: WARNINGS
      description: Number of test result warnings
    - default: "0"
      name: FAILURES
      description: Number of test result failures
    - default: ""
      name: NOTE
      description: Test note
  steps:
    - image: quay.io/redhat-appstudio/hacbs-test:stable
      script: |
        HACBS_TEST_OUTPUT=$(jq -rc \
          --arg date "$(date +%s)" \
          --arg TEST_SUITE_NAME "$(params.TEST_SUITE_NAME)" \
          --arg RESULT "$(params.RESULT)" \
          --arg SUCCESSES "$(params.SUCCESSES)" \
          --arg WARNINGS "$(params.WARNINGS)" \
          --arg FAILURES "$(params.FAILURES)" \
          --arg NOTE "$(params.NOTE)" \
          --null-input \
          '{namespace: $TEST_SUITE_NAME, result: $RESULT, timestamp: $date, failures: $FAILURES|tonumber, successes: $SUCCESSES|tonumber, warnings: $WARNINGS|tonumber, note: $NOTE}')
        echo "${HACBS_TEST_OUTPUT}" | tee $(results.HACBS_TEST_OUTPUT.path)
