apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: component-pipeline
spec:
  tasks:
    - name: task-success
      taskRef:
        name: test-output
        bundle: quay.io/kpavic/test-bundle:test-output
      params:
        - name: RESULT
          value: SUCCESS
    - name: task-failure
      taskRef:
        name: test-output
        bundle: quay.io/kpavic/test-bundle:test-output
      params:
        - name: RESULT
          value: FAILURE
    - name: task-skipped
      taskRef:
        name: test-output
        bundle: quay.io/kpavic/test-bundle:test-output
      params:
        - name: RESULT
          value: SKIPPED
